default:
  tags:
    - pppp

stages:
  - build
  - test

build:
  image: alpine
  stage: build
  script:
    - echo "Hello, $GITLAB_USER_LOGIN!"
    - echo "The University has general runners that will execute the pipeline available, but you must specify which docker image it needs to use as the environment to run in."
    - echo "See https://hub.docker.com/ for a listing of available images"

test:
  image: maven
  stage: test
  script:
    - echo "script lines are executed as bash commands in the main repository folder."
    - cd 2023Team06/azul
    - mvn verify
  artifacts:
    when: always
    reports:
      junit:
        - 2023Team06/azul/target/surefire-reports/TEST-*.xml
