default:
  tags:
    - pppp

stages:
  - build
  - test
  - test-coverage
  - report

build:
  image: maven
  stage: build
  script:
    - cd azul
    - mvn compile


unit-tests:
  image: maven
  stage: test
  coverage: '/Total.*?([0-9]{1,3})%/'
  script:
    - cd azul
    - mvn -Dtest="unit/**" test
    - grep -o -E 'Total<\/td><td\ class="bar">([^<])*<\/td><td\ class="ctr2">([^<])*<\/td>' target/site/jacoco/index.html || true
  artifacts:
    when: always
    reports:
      junit:
        - azul/target/surefire-reports/TEST-*.xml
    paths: # Upload the file as a generic job artifact
      - azul/target/site/jacoco/jacoco.xml

# reference from: https://docs.gitlab.com/ee/ci/testing/test_coverage_visualization.html
unit-tests-coverage:
  stage: test-coverage
  image: registry.gitlab.com/haynes/jacoco2cobertura:1.0.7
  script:
    - python /opt/cover2cover.py azul/target/site/jacoco/jacoco.xml $CI_PROJECT_DIR/src/main/java/ > azul/target/site/cobertura.xml
  needs: [ "unit-tests" ]
  artifacts:
    reports:
      coverage_report:
        coverage_format: cobertura
        path: azul/target/site/cobertura.xml

integration-tests:
  image: maven
  stage: test
  script:
    - mvn -Dtest="integration/**" test
  artifacts:
    when: always
    reports:
      junit:
        - target/surefire-reports/TEST-*.xml

system-tests:
  image: maven
  stage: test
  script:
    - mvn -Dtest="system/**" test
  artifacts:
    when: always
    reports:
      junit:
        - target/surefire-reports/TEST-*.xml


sigridpublish:
  stage: report
  image:
    name: softwareimprovementgroup/sigridci
  tags:
    - pppp

  script:
    - sigridci.py --customer utst --system P42023T06 --source . --publish
  allow_failure: true
  artifacts:
    paths:
      - "sigrid-ci-output/*"
    expire_in: 1 week
    when: always
  rules:
    - if: $CI_COMMIT_BRANCH == $CI_DEFAULT_BRANCH
