default:
  tags:
    - pppp

stages:
  - build
  - test
  - test-coverage
  - report

build:
  image: maven
  stage: build
  script:
    - cd azul
    - mvn compile

test:
  image: maven
  stage: test
  script:
    - cd azul
    - mvn test
  artifacts:
    when: always
    reports:
      junit:
        - azul/target/surefire-reports/TEST-*.xml
    paths:
      - azul/target/site/jacoco/jacoco.xml

# reference from: https://docs.gitlab.com/ee/ci/testing/test_coverage_visualization.html
test-coverage:
  stage: test-coverage
  image: registry.gitlab.com/haynes/jacoco2cobertura:1.0.7
  script:
    - python /opt/cover2cover.py azul/target/site/jacoco/jacoco.xml $CI_PROJECT_DIR/src/main/java/ > azul/target/site/cobertura.xml
  needs: [ "test" ]
  artifacts:
    reports:
      coverage_report:
        coverage_format: cobertura
        path: azul/target/site/cobertura.xml

sigridci:
  stage: report
  image:
    name: softwareimprovementgroup/sigridci
  tags:
    - pppp

  script:
    - sigridci.py --customer utst --system P42023T06 --source .
  allow_failure: true
  artifacts:
    paths:
      - "sigrid-ci-output/*"
    reports:
      junit: "sigrid-ci-output/sigridci-junit-format-report.xml"
    expire_in: 1 week
    when: always
  rules:
    - if: $CI_MERGE_REQUEST_ID

sigridpublish:
  stage: report
  image:
    name: softwareimprovementgroup/sigridci
  tags:
    - pppp

  script:
    - sigridci.py --customer utst --system P42023T06 --source . --publish
  allow_failure: true
  artifacts:
    paths:
      - "sigrid-ci-output/*"
    expire_in: 1 week
    when: always
  rules:
    - if: $CI_COMMIT_BRANCH == $CI_DEFAULT_BRANCH
