default:
  tags:
    - pppp

stages:
  - build
  - test

build:
  image: maven
  stage: build
  script:
    - mvn package

test:
  image: maven
  stage: test
  script:
    - cd 2023Team06/azul
    - mvn verify
  artifacts:
    when: always
    reports:
      junit:
        - 2023Team06/azul/target/surefire-reports/TEST-*.xml
